include ../config.mk

all::
	$(MAKE) -C kernel	all
#	$(MAKE) -C openpod_rq 		all
#	$(MAKE) test

install::
# Nothing

clean::
	$(MAKE) -C kernel   clean
#	$(MAKE) -C openpod_rq		clean
#	-rm *.a
