
==============
Directory tree
==============

GitHub project directory tree:

**src**
  Source code

  **openpod**

    Headers.

  **libs**

    Libraries of default functions and support subsystems for OpenPOD drivers.

  **os**

    Example bindings for some operating systems.

  **test**

    Regress test suite. Work in progress.

  **examples**

    Code examples.

  **modules**

    Loadable kernel modules. Mostly experimental.

  **barebones**

    Driver skeletons: starting points to implement or port a driver.



**dox**
  Sources for this document,

