include config.mk

default::
	@echo make all or make install
	@echo doing make all by default
	$(MAKE) all

install::
	# TODO

all::
	# TODO

clean::
	$(MAKE) -C libs clean
	$(MAKE) -C test clean

